name: Build and publish container

on:
  push:
    branches: 
    - "*"
    tags: 
    - "v*"
  workflow_dispatch:
    inputs:
      reason:
        description: 'Why ?'
        required: false
        default: ''

jobs:
  ghr_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log-in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push container image
        run: |
          IMAGE_ID=$(echo ghcr.io/${{ github.repository }} | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Build the image tags based on git branch and tag
          IMAGE_TAGS="-t ${IMAGE_ID}:${VERSION}"
          [ "$VERSION" == "main" ] && IMAGE_TAGS="${IMAGE_TAGS} -t ${IMAGE_ID}:latest"
          echo "${{ github.ref }}"
          # Build and Publish container image
          echo "Image tags: ${IMAGE_TAGS}"
          docker buildx build --push \
          ${IMAGE_TAGS} \
          --platform linux/amd64,linux/arm64 .